apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: simple-api
  name: simple-api-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-api
    spec:
      containers:
      - image: ipedrazas/simple-api
        name: simple-api
        ports:
        - name: simple-api
          containerPort: 5001
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5001
          initialDelaySeconds: 3
          timeoutSeconds: 1
      restartPolicy: Always
