apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: api-mongo
  name: api-mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api-mongo
    spec:
      containers:
      - image: ipedrazas/api-mongo
        name: api-mongo
        resources:
          limits:
            memory: "256Mi"
        env:
          - name: MONGO_HOST
            value: mongo.default.svc.cluster.local
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DBNAME
            value: "infracoders"
        ports:
        - name: api-mongo
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /_status/mongo/healthz
            port: 5000
          initialDelaySeconds: 3
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - sh
            - /app/readiness.sh
          initialDelaySeconds: 5
          timeoutSeconds: 1


      restartPolicy: Always


# curl -H "Content-Type: application/json" -X POST -d '{"title":"Hola", "body": "hello World!"}' http://172.17.4.202:30001/entries

