apiVersion: v1
kind: Service
metadata:
  name: api-mongo-svc
  labels:
    name: api-mongo-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
      protocol: TCP
  selector:
    name: api-mongo
