apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          timeoutSeconds: 1
        # If you activate the readinessProbe, the container never goes to
        # Ready state.
        # readinessProbe:
        #   tcpSocket:
        #     port: 27017
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
