apiVersion: v1
kind: Service
metadata:
  name: slowapi-svc
  labels:
    name: slowapi-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002
      protocol: TCP
  selector:
    name: slowapi
